### ISSUE TITLE
Help For The Wolf Among Us Please

### ISSUE THREAD

**Issue by deadeye201** [pashok6798/TTG_Tools#31]
hello, I want to port a Turkish language pack available on the internet to the ps4 version of the the wolf among us game this language pack normaly works on the pc version and i want port it in the ps4 version of game. Does your program work for the ps4 version of the game ? ı still don't understand how to use your program can you please help me

**Comment by MohammedXD29** [comment]
> hello, I want to port a Turkish language pack available on the internet to the ps4 version of the the wolf among us game this language pack normaly works on the pc version and i want port it in the ps4 version of game. Does your program work for the ps4 version of the game ? ı still don't understand how to use your program can you please help me

I'm Not @pashok6798 But Maybe I Can Help You , 
How Can I Help You ?

**Comment by deadeye201** [comment]
> > hello, I want to port a Turkish language pack available on the internet to the ps4 version of the the wolf among us game this language pack normaly works on the pc version and i want port it in the ps4 version of game. Does your program work for the ps4 version of the game ? ı still don't understand how to use your program can you please help me
> 
> I'm Not @pashok6798 But Maybe I Can Help You , How Can I Help You ?

thanks first thing i want to learn how to extract .ttarch2 files

**Comment by MohammedXD29** [comment]
Open It With Telltale Explorer And Select Save All Or Download This Tool https://www.mediafire.com/file/eba3duxtq7eltew/Telltale+Modding+Tools.rar/file But I Prefer To Use Telltale Explorer Because It's So Easy And If You Want To Rebuild The TTarch File Go To Archive Packer In TTG TOOLS And Choose "TTarch2" And Some Settings.

That's All !

**Comment by pashok6798** [comment]
Hi. I'm not sure about correct working with PS4 version because PS4 version uses swizzle method in texture and I don't know how insert that method in my tool so you need find tool that deswizzle texture after export DDS textures from D3DTX files.

You can also use ttarchext to extract files (need CMD):
ttarchext.exe -o 54 "C:\example\archive.ttarch2" "C:\unpacked files"


To build archive you can use ttarchext with command:
ttarchext.exe -b 54 "C:\example\new archive" "C:\unpacked modified files"
(Or ttarchext.exe by -V 7 54 "C:\example\new archive" "C:\unpacked modified files". I can't remember commands).
Also you can build archives with TTG Tools:
1. Select path to new archive (or you can select existed archive if you have created archive).
2. Select path to resource folder.
3. Select ttarch2 option.
4. Select version 1.
5. If in your archive have Lua scripts you can select "Don't encrypt Lua" for PS4 version.
6. If you want get smaller size of archive you can select "compress archive".

**Comment by deadeye201** [comment]
Thank you for all the informations

**Comment by deadeye201** [comment]
when i repack the file and i open the game its crash sadly what can i do ?

**Comment by MohammedXD29** [comment]
The New TTarch File You Have To Name It 0.TTarch2 And Don't Delete The Original TTarch File

**Comment by MohammedXD29** [comment]
Because When You Name It 0 The Game Will See It As A Patch

**Comment by pashok6798** [comment]
> when i repack the file and i open the game its crash sadly what can i do ?

You can try make lua scripts that loads your archive and set it next your archive.
Did you set option "Don't encrypt lua" while you build archive? Please show me your parameters in archive tool.

**Comment by deadeye201** [comment]
> > when i repack the file and i open the game its crash sadly what can i do ?
> 
> You can try make lua scripts that loads your archive and set it next your archive. Did you set option "Don't encrypt lua" while you build archive? Please show me your parameters in archive tool.

![3](https://user-images.githubusercontent.com/123601605/215279769-bfd9354c-cd9b-4194-879d-5b3dfb97ee1c.PNG)

**Comment by MohammedXD29** [comment]
Bro , I Told You You Have To Name The File 0 You don't Have To Delete Any Of Game Files That Is Way The Is Crashing Just Make A New File Don't Delete The Original File

**Comment by deadeye201** [comment]
> Bro , I Told You You Have To Name The File 0 You don't Have To Delete Any Of Game Files That Is Way The Is Crashing Just Make A New File Don't Delete The Original File

I also tried to do as you said, but normally it should be Turkish, but I still couldn't understand it in English.

**Comment by MohammedXD29** [comment]
Then Don't Create TTarch Just Put The Font And Landb File In The Game File Folder Pack Without TTarch And It Should Work

**Comment by deadeye201** [comment]
> Then Don't Create TTarch Just Put The Font And Landb File In The Game File Folder Pack Without TTarch And It Should Work

thanks for the info now worked but now i have this problem 
![The Wolf Among Us_20230129003814](https://user-images.githubusercontent.com/123601605/215292296-5d8c80cd-eb1b-445b-b4a6-dab29c562b1d.jpg)
![The Wolf Among Us_20230129003832](https://user-images.githubusercontent.com/123601605/215292299-62228828-06fd-4bcd-be3c-e0dafa24de5d.jpg)

**Comment by MohammedXD29** [comment]
When You Clicked On Import Encrypt In TTG TOOLS There Was An Option You Have To Enable It 

Name Of The Option "Unicode Support Is On"

**Comment by MohammedXD29** [comment]
You Have To Enable It And After You Enable It
Import The Files

**Comment by deadeye201** [comment]
> You Have To Enable It And After You Enable It Import The Files

I extracted the ttarch and using ttg tools decrypt and export it then i enabled the unicode support is on option after that i used encyrpt pack import option and then i copied the files in the output folder and copied the files in the game pack file is that right ?

**Comment by deadeye201** [comment]
sadly not worked stucked in the black screen  which ttarch file have the font files of the game?

**Comment by MohammedXD29** [comment]
I Don't Know 😶 Can You Send Me The Turkish Files ?

**Comment by MohammedXD29** [comment]
I Will Try

**Comment by deadeye201** [comment]
> I Don't Know 😶 Can You Send Me The Turkish Files ?

https://drive.google.com/file/d/1cUXh_HmA98rbKtKokKXCG5CSJGtAk8-V/view?usp=share_link

**Comment by pashok6798** [comment]
@deadeye201 Since The Wolf Among Us and The Walking Dead season two you need create TTARCH2 archives and make own lua scripts that load your modified files. In lua scripts you need set priority, needed tags and name of you ttarch2 archive. I don't recommend put all you modified files in Archive folder because some files with common names will make a lot of problems in next episodes.

**Comment by pashok6798** [comment]
> > > when i repack the file and i open the game its crash sadly what can i do ?
> > 
> > 
> > You can try make lua scripts that loads your archive and set it next your archive. Did you set option "Don't encrypt lua" while you build archive? Please show me your parameters in archive tool.
> 
> ![3](https://user-images.githubusercontent.com/123601605/215279769-bfd9354c-cd9b-4194-879d-5b3dfb97ee1c.PNG)

Did you extract all resources or only landb files, for example? Maybe game couldn't find needed files for game engine.

**Comment by deadeye201** [comment]
I've tried extract all files and copy it in the Pack folder not worked stuck in black screen

**Comment by pashok6798** [comment]
Remove unpacked resources from Pack folder and restore original files (if you have steam version just check files and steam download needed files). You need create own ttarch2 archive and make own Lua script. I heard that on PS4 version Lua scripts for archive aren't encrypted and it looks just like text, not like binary files.

**Comment by MohammedXD29** [comment]
I Remember That You Can Create Patch Files But I Don't Know What You Should Name It

**Comment by deadeye201** [comment]
How can I make my own lua script for the ps4 version of the game?
